services:
  baizhi-serve:
    image: baizhi-serve
    container_name: baizhi-serve
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - baizhi

  baizhi-ui:
    image: baizhi-ui
    container_name: "baizhi-ui"
    depends_on:
      baizhi-serve:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - baizhi

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_DATABASE=baizhi
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$$MYSQL_ROOT_USER", "-p$$MYSQL_ROOT_PASSWORD",  "ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 16
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ../../mysql/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
      - ../../mysql/init.d:/docker-entrypoint-initdb.d
    networks:
      - baizhi

  redis:
    image: bitnami/redis:6.0
    container_name: redis
    environment:
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=123456
    ports:
      - 6379:6379
    networks:
      - baizhi

networks:
  baizhi:
    driver: bridge
